server.port=8585
server.servlet.context-path=/workintech

# Spring DevTools
spring.devtools.restart.enabled=true

# Actuator
management.info.env.enabled=true
management.endpoints.web.exposure.include=info,health,mappings

# Info endpoint
info.app.name=s17d2-spring-di
info.app.description=Spring Boot Dependency Injection Application
info.app.version=0.0.1-SNAPSHOT
